### ISSUE TITLE
change autoplay state

### ISSUE THREAD

**Issue by abdulrahmanmajeed** [PierfrancescoSoffritti/AndroidYouTubePlayer#32] opened 2017-06-29 21:30 UTC
how to change autoplay state ??

**Comment by PierfrancescoSoffritti** [comment] 2017-06-29 21:46
closed as duplicate of [#30](https://github.com/PierfrancescoSoffritti/AndroidYouTubePlayer/issues/30)

**Comment by abdulrahmanmajeed** [comment] 2017-06-29 21:52
would u please comment why u close without any suggestion :(

**Comment by PierfrancescoSoffritti** [comment] 2017-06-29 21:56
closed as duplicate of [#30](https://github.com/PierfrancescoSoffritti/AndroidYouTubePlayer/issues/30)

**Closed by PierfrancescoSoffritti** 2017-06-29 21:56 UTC
